{{- if .Values.ingress.enabled -}}
{{- $fullName := include "espocrm.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "espocrm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.sessionAffinity.enabled }}
    {{- if eq .Values.ingress.sessionAffinity.type "traefik" }}
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: {{ .Values.ingress.sessionAffinity.cookieName | quote }}
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: {{ .Values.ingress.sessionAffinity.httpOnly | quote }}
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: {{ .Values.ingress.sessionAffinity.secure | quote }}
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: {{ .Values.ingress.sessionAffinity.sameSite | quote }}
    {{- else if eq .Values.ingress.sessionAffinity.type "nginx" }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: {{ .Values.ingress.sessionAffinity.cookieName | quote }}
    nginx.ingress.kubernetes.io/session-cookie-max-age: "1800"
    nginx.ingress.kubernetes.io/session-cookie-samesite: {{ .Values.ingress.sessionAffinity.sameSite | title | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  name: http
          {{- if $.Values.websocket.enabled }}
          - path: /wss
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-websocket
                port:
                  name: websocket
          {{- end }}
    {{- end }}
{{- end }}
