{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "espocrm.databaseSecretName" . }}
  labels:
    {{- include "espocrm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.externalDatabase.secretKey }}: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
